-- MySQL Script generated by MySQL Workbench
-- Fri Sep 20 23:22:45 2024
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema DB_N
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema DB_N
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `DB_N` DEFAULT CHARACTER SET utf8 ;
USE `DB_N` ;

-- -----------------------------------------------------
-- Table `DB_N`.`Clientes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `DB_N`.`Clientes` (
  `idClientes` INT NOT NULL AUTO_INCREMENT,
  `Nombre` VARCHAR(45) NOT NULL,
  `Apellido` VARCHAR(45) NOT NULL,
  `email` VARCHAR(45) NOT NULL,
  `telefono` VARCHAR(45) NOT NULL,
  `direccion` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idClientes`))
ENGINE = InnoDB;

-- -----------------------------------------------------
-- Table `DB_N`.`Servicios`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `DB_N`.`Servicios` (
  `idServicios` INT NOT NULL AUTO_INCREMENT,
  `nombre_servicio` VARCHAR(60) NOT NULL,
  `hora_inicio` DATETIME NULL,
  `duracion` VARCHAR(45) NOT NULL,
  `descripcion` VARCHAR(100) NOT NULL,
  `Cupos_idCupos` INT NOT NULL,
  PRIMARY KEY (`idServicios`, `Cupos_idCupos`))
ENGINE = InnoDB;

-- -----------------------------------------------------
-- Table `DB_N`.`Precios`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `DB_N`.`Precios` (
  `idPrecios` INT NOT NULL AUTO_INCREMENT,
  `Monto` DECIMAL(8) NOT NULL,
  `Servicios_idServicios` INT NOT NULL,
  PRIMARY KEY (`idPrecios`, `Servicios_idServicios`),
  INDEX `fk_Precios_Servicios1_idx` (`Servicios_idServicios` ASC) VISIBLE,
  CONSTRAINT `fk_Precios_Servicios1`
    FOREIGN KEY (`Servicios_idServicios`)
    REFERENCES `DB_N`.`Servicios` (`idServicios`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

-- -----------------------------------------------------
-- Table `DB_N`.`Cupos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `DB_N`.`Cupos` (
  `idCupos` INT NOT NULL AUTO_INCREMENT,
  `cupos_total` VARCHAR(45) NOT NULL,
  `cupo_disponible` VARCHAR(45) NOT NULL,
  `Servicios_idServicios` INT NOT NULL,
  PRIMARY KEY (`idCupos`, `Servicios_idServicios`),
  INDEX `fk_Cupos_Servicios1_idx` (`Servicios_idServicios` ASC) VISIBLE,
  CONSTRAINT `fk_Cupos_Servicios1`
    FOREIGN KEY (`Servicios_idServicios`)
    REFERENCES `DB_N`.`Servicios` (`idServicios`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

-- -----------------------------------------------------
-- Table `DB_N`.`Citas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `DB_N`.`Citas` (
  `idCItas` INT NOT NULL AUTO_INCREMENT,
  `fecha_cita` DATETIME NOT NULL,
  `Clientes_idClientes` INT NOT NULL,
  `Servicios_idServicios` INT NOT NULL,
  PRIMARY KEY (`idCItas`, `Clientes_idClientes`, `Servicios_idServicios`),
  INDEX `fk_CItas_Clientes_idx` (`Clientes_idClientes` ASC) VISIBLE,
  INDEX `fk_CItas_Servicios1_idx` (`Servicios_idServicios` ASC) VISIBLE,
  CONSTRAINT `fk_CItas_Clientes`
    FOREIGN KEY (`Clientes_idClientes`)
    REFERENCES `DB_N`.`Clientes` (`idClientes`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_CItas_Servicios1`
    FOREIGN KEY (`Servicios_idServicios`)
    REFERENCES `DB_N`.`Servicios` (`idServicios`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

-- -----------------------------------------------------
-- Table `DB_N`.`Factura`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `DB_N`.`Factura` (
  `idFactura` INT NOT NULL AUTO_INCREMENT,
  `fecha_factura` DATETIME NOT NULL,
  `Clientes_idClientes` INT NOT NULL,
  `total_factura` DECIMAL NOT NULL,
  PRIMARY KEY (`idFactura`, `Clientes_idClientes`),
  INDEX `fk_Factura_Clientes1_idx` (`Clientes_idClientes` ASC) VISIBLE,
  CONSTRAINT `fk_Factura_Clientes1`
    FOREIGN KEY (`Clientes_idClientes`)
    REFERENCES `DB_N`.`Clientes` (`idClientes`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

-- -----------------------------------------------------
-- Table `DB_N`.`Detalle_factura`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `DB_N`.`Detalle_factura` (
  `idDetalle_factura` INT NOT NULL AUTO_INCREMENT,
  `cantidad` VARCHAR(45) NOT NULL,
  `descripcion` VARCHAR(45) NOT NULL,
  `Factura_idFactura` INT NOT NULL,
  PRIMARY KEY (`idDetalle_factura`, `Factura_idFactura`),
  INDEX `fk_Detalle_factura_Factura1_idx` (`Factura_idFactura` ASC) VISIBLE,
  CONSTRAINT `fk_Detalle_factura_Factura1`
    FOREIGN KEY (`Factura_idFactura`)
    REFERENCES `DB_N`.`Factura` (`idFactura`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

-- -----------------------------------------------------
-- Table `DB_N`.`Pago`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `DB_N`.`Pago` (
  `idPago` INT NOT NULL AUTO_INCREMENT,
  `monto_total` VARCHAR(45) NOT NULL,
  `metodo_pago` VARCHAR(45) NOT NULL,
  `Factura_idFactura` INT NOT NULL,
  PRIMARY KEY (`idPago`, `Factura_idFactura`),
  INDEX `fk_Pago_Factura1_idx` (`Factura_idFactura` ASC) VISIBLE,
  CONSTRAINT `fk_Pago_Factura1`
    FOREIGN KEY (`Factura_idFactura`)
    REFERENCES `DB_N`.`Factura` (`idFactura`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

-- -----------------------------------------------------
-- Table `DB_N`.`Contraseña`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `DB_N`.`Contraseña` (
  `idContraseña` INT NOT NULL AUTO_INCREMENT,
  `Password` VARCHAR(45) NULL,
  PRIMARY KEY (`idContraseña`))
ENGINE = InnoDB;

-- -----------------------------------------------------
-- Table `DB_N`.`Administrador`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `DB_N`.`Administrador` (
  `IdAdmin` INT NOT NULL AUTO_INCREMENT,
  `UserAdmin` VARCHAR(45) NOT NULL,
  `Contraseña_idContraseña` INT NOT NULL,
  PRIMARY KEY (`IdAdmin`, `Contraseña_idContraseña`),
  INDEX `fk_Administrador_Contraseña1_idx` (`Contraseña_idContraseña` ASC) VISIBLE,
  CONSTRAINT `fk_Administrador_Contraseña1`
    FOREIGN KEY (`Contraseña_idContraseña`)
    REFERENCES `DB_N`.`Contraseña` (`idContraseña`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
